"""empty message

Revision ID: 36c5c6d8ea9a
Revises: e77488c42441
Create Date: 2017-11-01 13:44:34.956309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c5c6d8ea9a'
down_revision = 'e77488c42441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('comment_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'comment_num')
    # ### end Alembic commands ###
